### ISSUE TITLE
Exposed sensitive info

### ISSUE THREAD

**Issue by AaronGulman** [manuel920506/clinica-bravo-app#1]
Hi ,
Please correct me if I’m wrong but I noticed that the `.env.production` file in the repository contains sensitive information, including an API URL. This file is currently being committed to version control, which poses a security risk, even if the data is primarily for development purposes.

Given your experience I’m genuinely  curious what’s the purpose of committing a .env file  in your case or was it an honest mistake ? I’d really appreciate a reply !

**Comment by manuel920506** [comment]
You are right. I didn't care about this because I was just testing. One way to fix this is to put these files in a .gitignore rule, although there are many others. Happy coding!
